spring:
  config:
    activate:
      on-profile: prod
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: rds-imported-schema
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    com.kangaroo.sparring: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: INFO
