spring:
  config:
    activate:
      on-profile: dev
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.kangaroo.sparring: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

app:
  auth:
    signup:
      require-email-verification: false
